dist: trusty
sudo: required
services:
  - docker
addons:
  firefox: latest
  chrome: stable
language: node_js
node_js: stable
install: echo "no install yet"
before_script:
  - npm --version
  - docker --version
  - docker run hello-world
  - svn --version
  - npm install -g yarn
  - yarn --version
  - yarn global add polymer-cli
  - echo not yet polymer --version
  - echo not yet polymer analyze
  - echo not yet polymer install
  - svn export https://github.com/e7dal/weaviate/trunk/docker ~/tryweaviate
  - cd ~/tryweaviate
  - bash run-services.sh
  - cd -
script:
  - xvfb-run polymer test
cache:
  directories:
  - node_modules
  - bower_components
