dist: trusty
sudo: required
services:
  - docker
addons:
  firefox: latest
  chrome: stable
language: node_js
node_js: "lts/boron"
install: echo "no install yet"
before_script:
  - npm --version
  - docker --version
  - docker run hello-world
  - svn --version
  - npm install -g yarn
  - yarn --version
  - yarn global add polymer-cli
  - echo not yet polymer --version
  - echo not yet polymer analyze
  - echo not yet polymer install
  - mkdir ~/tryweaviate
  - cd ~/tryweaviate
  - wget -q -O Dockerfile https://raw.githubusercontent.com/e7dal/weaviate/master/docker/Dockerfile
  - wget -q -O run-services.sh https://raw.githubusercontent.com/e7dal/weaviate/master/docker/run-services.sh
  - sed -i 's/# set -x/set -x/' run-services.sh
  - sudo bash run-services.sh
  - sudo docker ps -a
  - sudo docker exec -it weaviate cat /var/weaviate/first_run.log
  - cd -
  - pwd
script:
  - xvfb-run polymer test
cache:
  directories:
  - node_modules
  - bower_components
