sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - npm install -g polymer-cli
script:
  - xvfb-run npm test
  - xvfb-run npm run test:integration
  - xvfb-run polymer test

