dist: trusty
sudo: required
services:
  - docker
addons:
  firefox: latest
  chrome: stable
language: node_js
node_js: stable
before_script:
  - npm --version
  - npm install -g bower polylint web-component-tester
  - docker --version
  - docker run hello-world
  - npm install -g yarn
  - yarn --version
  - polymer --version
script:
  - xvfb-run wct
cache:
  directories:
  - node_modules
  - bower_components
