dist: trusty
sudo: required
services:
  - docker
addons:
  firefox: latest
  chrome: stable
language: node_js
node_js: stable
install: echo "no install yet"
before_script:
  - npm --version
  - docker --version
  - docker run hello-world
  - npm install -g yarn
  - yarn --version
  - yarn add polymer
  - polymer --version
  - polymer analyze
  - polymer install
script:
  - xvfb-run polymer test
cache:
  directories:
  - node_modules
  - bower_components
