sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
  - "8"
before_script:
  - npm --version
  - docker --version
  - docker run hello-world
  - npm install -g yarn
  - yarn --version
  - yarn global add bower
  - yarn global add polymer-cli
  - bower --version
  - polymer --version
  - bower install
  - yarn install
script:
  - xvfb-run npm test
  - xvfb-run npm run test:integration
  - xvfb-run polymer test

